// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: stream/stream.proto

package stream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamService_StartStream_FullMethodName        = "/stream.StreamService/StartStream"
	StreamService_StopStream_FullMethodName         = "/stream.StreamService/StopStream"
	StreamService_GetStreamStatus_FullMethodName    = "/stream.StreamService/GetStreamStatus"
	StreamService_PauseStream_FullMethodName        = "/stream.StreamService/PauseStream"
	StreamService_ResumeStream_FullMethodName       = "/stream.StreamService/ResumeStream"
	StreamService_SeekStream_FullMethodName         = "/stream.StreamService/SeekStream"
	StreamService_GetQualities_FullMethodName       = "/stream.StreamService/GetQualities"
	StreamService_SetQuality_FullMethodName         = "/stream.StreamService/SetQuality"
	StreamService_GetSubtitles_FullMethodName       = "/stream.StreamService/GetSubtitles"
	StreamService_GetSubtitlesByLang_FullMethodName = "/stream.StreamService/GetSubtitlesByLang"
	StreamService_GetActiveSessions_FullMethodName  = "/stream.StreamService/GetActiveSessions"
	StreamService_GetPreview_FullMethodName         = "/stream.StreamService/GetPreview"
)

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamServiceClient interface {
	StartStream(ctx context.Context, in *StartStreamRequest, opts ...grpc.CallOption) (*StartStreamResponse, error)
	StopStream(ctx context.Context, in *StopStreamRequest, opts ...grpc.CallOption) (*StopStreamResponse, error)
	GetStreamStatus(ctx context.Context, in *GetStreamStatusRequest, opts ...grpc.CallOption) (*GetStreamStatusResponse, error)
	PauseStream(ctx context.Context, in *PauseStreamRequest, opts ...grpc.CallOption) (*PauseStreamResponse, error)
	ResumeStream(ctx context.Context, in *ResumeStreamRequest, opts ...grpc.CallOption) (*ResumeStreamResponse, error)
	SeekStream(ctx context.Context, in *SeekStreamRequest, opts ...grpc.CallOption) (*SeekStreamResponse, error)
	GetQualities(ctx context.Context, in *GetQualitiesRequest, opts ...grpc.CallOption) (*GetQualitiesResponse, error)
	SetQuality(ctx context.Context, in *SetQualityRequest, opts ...grpc.CallOption) (*SetQualityResponse, error)
	GetSubtitles(ctx context.Context, in *GetSubtitlesRequest, opts ...grpc.CallOption) (*GetSubtitlesResponse, error)
	GetSubtitlesByLang(ctx context.Context, in *GetSubtitlesByLangRequest, opts ...grpc.CallOption) (*GetSubtitlesByLangResponse, error)
	GetActiveSessions(ctx context.Context, in *GetActiveSessionsRequest, opts ...grpc.CallOption) (*GetActiveSessionsResponse, error)
	GetPreview(ctx context.Context, in *GetPreviewRequest, opts ...grpc.CallOption) (*GetPreviewResponse, error)
}

type streamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamServiceClient(cc grpc.ClientConnInterface) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) StartStream(ctx context.Context, in *StartStreamRequest, opts ...grpc.CallOption) (*StartStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartStreamResponse)
	err := c.cc.Invoke(ctx, StreamService_StartStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) StopStream(ctx context.Context, in *StopStreamRequest, opts ...grpc.CallOption) (*StopStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopStreamResponse)
	err := c.cc.Invoke(ctx, StreamService_StopStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) GetStreamStatus(ctx context.Context, in *GetStreamStatusRequest, opts ...grpc.CallOption) (*GetStreamStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStreamStatusResponse)
	err := c.cc.Invoke(ctx, StreamService_GetStreamStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) PauseStream(ctx context.Context, in *PauseStreamRequest, opts ...grpc.CallOption) (*PauseStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseStreamResponse)
	err := c.cc.Invoke(ctx, StreamService_PauseStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) ResumeStream(ctx context.Context, in *ResumeStreamRequest, opts ...grpc.CallOption) (*ResumeStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeStreamResponse)
	err := c.cc.Invoke(ctx, StreamService_ResumeStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) SeekStream(ctx context.Context, in *SeekStreamRequest, opts ...grpc.CallOption) (*SeekStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeekStreamResponse)
	err := c.cc.Invoke(ctx, StreamService_SeekStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) GetQualities(ctx context.Context, in *GetQualitiesRequest, opts ...grpc.CallOption) (*GetQualitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQualitiesResponse)
	err := c.cc.Invoke(ctx, StreamService_GetQualities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) SetQuality(ctx context.Context, in *SetQualityRequest, opts ...grpc.CallOption) (*SetQualityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetQualityResponse)
	err := c.cc.Invoke(ctx, StreamService_SetQuality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) GetSubtitles(ctx context.Context, in *GetSubtitlesRequest, opts ...grpc.CallOption) (*GetSubtitlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubtitlesResponse)
	err := c.cc.Invoke(ctx, StreamService_GetSubtitles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) GetSubtitlesByLang(ctx context.Context, in *GetSubtitlesByLangRequest, opts ...grpc.CallOption) (*GetSubtitlesByLangResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubtitlesByLangResponse)
	err := c.cc.Invoke(ctx, StreamService_GetSubtitlesByLang_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) GetActiveSessions(ctx context.Context, in *GetActiveSessionsRequest, opts ...grpc.CallOption) (*GetActiveSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveSessionsResponse)
	err := c.cc.Invoke(ctx, StreamService_GetActiveSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) GetPreview(ctx context.Context, in *GetPreviewRequest, opts ...grpc.CallOption) (*GetPreviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPreviewResponse)
	err := c.cc.Invoke(ctx, StreamService_GetPreview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamServiceServer is the server API for StreamService service.
// All implementations must embed UnimplementedStreamServiceServer
// for forward compatibility.
type StreamServiceServer interface {
	StartStream(context.Context, *StartStreamRequest) (*StartStreamResponse, error)
	StopStream(context.Context, *StopStreamRequest) (*StopStreamResponse, error)
	GetStreamStatus(context.Context, *GetStreamStatusRequest) (*GetStreamStatusResponse, error)
	PauseStream(context.Context, *PauseStreamRequest) (*PauseStreamResponse, error)
	ResumeStream(context.Context, *ResumeStreamRequest) (*ResumeStreamResponse, error)
	SeekStream(context.Context, *SeekStreamRequest) (*SeekStreamResponse, error)
	GetQualities(context.Context, *GetQualitiesRequest) (*GetQualitiesResponse, error)
	SetQuality(context.Context, *SetQualityRequest) (*SetQualityResponse, error)
	GetSubtitles(context.Context, *GetSubtitlesRequest) (*GetSubtitlesResponse, error)
	GetSubtitlesByLang(context.Context, *GetSubtitlesByLangRequest) (*GetSubtitlesByLangResponse, error)
	GetActiveSessions(context.Context, *GetActiveSessionsRequest) (*GetActiveSessionsResponse, error)
	GetPreview(context.Context, *GetPreviewRequest) (*GetPreviewResponse, error)
	mustEmbedUnimplementedStreamServiceServer()
}

// UnimplementedStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamServiceServer struct{}

func (UnimplementedStreamServiceServer) StartStream(context.Context, *StartStreamRequest) (*StartStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartStream not implemented")
}
func (UnimplementedStreamServiceServer) StopStream(context.Context, *StopStreamRequest) (*StopStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopStream not implemented")
}
func (UnimplementedStreamServiceServer) GetStreamStatus(context.Context, *GetStreamStatusRequest) (*GetStreamStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStreamStatus not implemented")
}
func (UnimplementedStreamServiceServer) PauseStream(context.Context, *PauseStreamRequest) (*PauseStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseStream not implemented")
}
func (UnimplementedStreamServiceServer) ResumeStream(context.Context, *ResumeStreamRequest) (*ResumeStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeStream not implemented")
}
func (UnimplementedStreamServiceServer) SeekStream(context.Context, *SeekStreamRequest) (*SeekStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SeekStream not implemented")
}
func (UnimplementedStreamServiceServer) GetQualities(context.Context, *GetQualitiesRequest) (*GetQualitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQualities not implemented")
}
func (UnimplementedStreamServiceServer) SetQuality(context.Context, *SetQualityRequest) (*SetQualityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetQuality not implemented")
}
func (UnimplementedStreamServiceServer) GetSubtitles(context.Context, *GetSubtitlesRequest) (*GetSubtitlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubtitles not implemented")
}
func (UnimplementedStreamServiceServer) GetSubtitlesByLang(context.Context, *GetSubtitlesByLangRequest) (*GetSubtitlesByLangResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubtitlesByLang not implemented")
}
func (UnimplementedStreamServiceServer) GetActiveSessions(context.Context, *GetActiveSessionsRequest) (*GetActiveSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveSessions not implemented")
}
func (UnimplementedStreamServiceServer) GetPreview(context.Context, *GetPreviewRequest) (*GetPreviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPreview not implemented")
}
func (UnimplementedStreamServiceServer) mustEmbedUnimplementedStreamServiceServer() {}
func (UnimplementedStreamServiceServer) testEmbeddedByValue()                       {}

// UnsafeStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServiceServer will
// result in compilation errors.
type UnsafeStreamServiceServer interface {
	mustEmbedUnimplementedStreamServiceServer()
}

func RegisterStreamServiceServer(s grpc.ServiceRegistrar, srv StreamServiceServer) {
	// If the following call pancis, it indicates UnimplementedStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamService_ServiceDesc, srv)
}

func _StreamService_StartStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).StartStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_StartStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).StartStream(ctx, req.(*StartStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_StopStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).StopStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_StopStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).StopStream(ctx, req.(*StopStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_GetStreamStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetStreamStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_GetStreamStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetStreamStatus(ctx, req.(*GetStreamStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_PauseStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).PauseStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_PauseStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).PauseStream(ctx, req.(*PauseStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_ResumeStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).ResumeStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_ResumeStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).ResumeStream(ctx, req.(*ResumeStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_SeekStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeekStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).SeekStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_SeekStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).SeekStream(ctx, req.(*SeekStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_GetQualities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQualitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetQualities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_GetQualities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetQualities(ctx, req.(*GetQualitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_SetQuality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetQualityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).SetQuality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_SetQuality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).SetQuality(ctx, req.(*SetQualityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_GetSubtitles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubtitlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetSubtitles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_GetSubtitles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetSubtitles(ctx, req.(*GetSubtitlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_GetSubtitlesByLang_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubtitlesByLangRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetSubtitlesByLang(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_GetSubtitlesByLang_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetSubtitlesByLang(ctx, req.(*GetSubtitlesByLangRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_GetActiveSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetActiveSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_GetActiveSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetActiveSessions(ctx, req.(*GetActiveSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_GetPreview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetPreview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_GetPreview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetPreview(ctx, req.(*GetPreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamService_ServiceDesc is the grpc.ServiceDesc for StreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartStream",
			Handler:    _StreamService_StartStream_Handler,
		},
		{
			MethodName: "StopStream",
			Handler:    _StreamService_StopStream_Handler,
		},
		{
			MethodName: "GetStreamStatus",
			Handler:    _StreamService_GetStreamStatus_Handler,
		},
		{
			MethodName: "PauseStream",
			Handler:    _StreamService_PauseStream_Handler,
		},
		{
			MethodName: "ResumeStream",
			Handler:    _StreamService_ResumeStream_Handler,
		},
		{
			MethodName: "SeekStream",
			Handler:    _StreamService_SeekStream_Handler,
		},
		{
			MethodName: "GetQualities",
			Handler:    _StreamService_GetQualities_Handler,
		},
		{
			MethodName: "SetQuality",
			Handler:    _StreamService_SetQuality_Handler,
		},
		{
			MethodName: "GetSubtitles",
			Handler:    _StreamService_GetSubtitles_Handler,
		},
		{
			MethodName: "GetSubtitlesByLang",
			Handler:    _StreamService_GetSubtitlesByLang_Handler,
		},
		{
			MethodName: "GetActiveSessions",
			Handler:    _StreamService_GetActiveSessions_Handler,
		},
		{
			MethodName: "GetPreview",
			Handler:    _StreamService_GetPreview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stream/stream.proto",
}
