// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: stream/stream.proto

package stream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionStatus int32

const (
	SessionStatus_UNKNOWN  SessionStatus = 0
	SessionStatus_PLAYING  SessionStatus = 1
	SessionStatus_PAUSED   SessionStatus = 2
	SessionStatus_FINISHED SessionStatus = 3
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "PLAYING",
		2: "PAUSED",
		3: "FINISHED",
	}
	SessionStatus_value = map[string]int32{
		"UNKNOWN":  0,
		"PLAYING":  1,
		"PAUSED":   2,
		"FINISHED": 3,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_stream_stream_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_stream_stream_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{0}
}

type Quality int32

const (
	Quality_Q_480P  Quality = 0
	Quality_Q_720P  Quality = 1
	Quality_Q_1080P Quality = 2
)

// Enum value maps for Quality.
var (
	Quality_name = map[int32]string{
		0: "Q_480P",
		1: "Q_720P",
		2: "Q_1080P",
	}
	Quality_value = map[string]int32{
		"Q_480P":  0,
		"Q_720P":  1,
		"Q_1080P": 2,
	}
)

func (x Quality) Enum() *Quality {
	p := new(Quality)
	*p = x
	return p
}

func (x Quality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Quality) Descriptor() protoreflect.EnumDescriptor {
	return file_stream_stream_proto_enumTypes[1].Descriptor()
}

func (Quality) Type() protoreflect.EnumType {
	return &file_stream_stream_proto_enumTypes[1]
}

func (x Quality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Quality.Descriptor instead.
func (Quality) EnumDescriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{1}
}

type Session struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId         string                 `protobuf:"bytes,3,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	PositionSeconds int32                  `protobuf:"varint,4,opt,name=position_seconds,json=positionSeconds,proto3" json:"position_seconds,omitempty"`
	Quality         Quality                `protobuf:"varint,5,opt,name=quality,proto3,enum=stream.Quality" json:"quality,omitempty"`
	Status          SessionStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=stream.SessionStatus" json:"status,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_stream_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *Session) GetPositionSeconds() int32 {
	if x != nil {
		return x.PositionSeconds
	}
	return 0
}

func (x *Session) GetQuality() Quality {
	if x != nil {
		return x.Quality
	}
	return Quality_Q_480P
}

func (x *Session) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_UNKNOWN
}

func (x *Session) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Session) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Subtitle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lang          string                 `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	FileUrl       string                 `protobuf:"bytes,3,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subtitle) Reset() {
	*x = Subtitle{}
	mi := &file_stream_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subtitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subtitle) ProtoMessage() {}

func (x *Subtitle) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subtitle.ProtoReflect.Descriptor instead.
func (*Subtitle) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{1}
}

func (x *Subtitle) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *Subtitle) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Subtitle) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

type StartStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId       string                 `protobuf:"bytes,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Quality       Quality                `protobuf:"varint,3,opt,name=quality,proto3,enum=stream.Quality" json:"quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartStreamRequest) Reset() {
	*x = StartStreamRequest{}
	mi := &file_stream_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStreamRequest) ProtoMessage() {}

func (x *StartStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStreamRequest.ProtoReflect.Descriptor instead.
func (*StartStreamRequest) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{2}
}

func (x *StartStreamRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartStreamRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *StartStreamRequest) GetQuality() Quality {
	if x != nil {
		return x.Quality
	}
	return Quality_Q_480P
}

type StartStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartStreamResponse) Reset() {
	*x = StartStreamResponse{}
	mi := &file_stream_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStreamResponse) ProtoMessage() {}

func (x *StartStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStreamResponse.ProtoReflect.Descriptor instead.
func (*StartStreamResponse) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{3}
}

func (x *StartStreamResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type StopStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopStreamRequest) Reset() {
	*x = StopStreamRequest{}
	mi := &file_stream_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStreamRequest) ProtoMessage() {}

func (x *StopStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStreamRequest.ProtoReflect.Descriptor instead.
func (*StopStreamRequest) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{4}
}

func (x *StopStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StopStreamResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	WatchedSeconds int32                  `protobuf:"varint,2,opt,name=watched_seconds,json=watchedSeconds,proto3" json:"watched_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StopStreamResponse) Reset() {
	*x = StopStreamResponse{}
	mi := &file_stream_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStreamResponse) ProtoMessage() {}

func (x *StopStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStreamResponse.ProtoReflect.Descriptor instead.
func (*StopStreamResponse) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{5}
}

func (x *StopStreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopStreamResponse) GetWatchedSeconds() int32 {
	if x != nil {
		return x.WatchedSeconds
	}
	return 0
}

type GetStreamStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamStatusRequest) Reset() {
	*x = GetStreamStatusRequest{}
	mi := &file_stream_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamStatusRequest) ProtoMessage() {}

func (x *GetStreamStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStreamStatusRequest) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{6}
}

func (x *GetStreamStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetStreamStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamStatusResponse) Reset() {
	*x = GetStreamStatusResponse{}
	mi := &file_stream_stream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamStatusResponse) ProtoMessage() {}

func (x *GetStreamStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStreamStatusResponse) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{7}
}

func (x *GetStreamStatusResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type PauseStreamRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PositionSeconds int32                  `protobuf:"varint,2,opt,name=position_seconds,json=positionSeconds,proto3" json:"position_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PauseStreamRequest) Reset() {
	*x = PauseStreamRequest{}
	mi := &file_stream_stream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseStreamRequest) ProtoMessage() {}

func (x *PauseStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseStreamRequest.ProtoReflect.Descriptor instead.
func (*PauseStreamRequest) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{8}
}

func (x *PauseStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PauseStreamRequest) GetPositionSeconds() int32 {
	if x != nil {
		return x.PositionSeconds
	}
	return 0
}

type PauseStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseStreamResponse) Reset() {
	*x = PauseStreamResponse{}
	mi := &file_stream_stream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseStreamResponse) ProtoMessage() {}

func (x *PauseStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseStreamResponse.ProtoReflect.Descriptor instead.
func (*PauseStreamResponse) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{9}
}

func (x *PauseStreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ResumeStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeStreamRequest) Reset() {
	*x = ResumeStreamRequest{}
	mi := &file_stream_stream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeStreamRequest) ProtoMessage() {}

func (x *ResumeStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeStreamRequest.ProtoReflect.Descriptor instead.
func (*ResumeStreamRequest) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{10}
}

func (x *ResumeStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ResumeStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeStreamResponse) Reset() {
	*x = ResumeStreamResponse{}
	mi := &file_stream_stream_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeStreamResponse) ProtoMessage() {}

func (x *ResumeStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeStreamResponse.ProtoReflect.Descriptor instead.
func (*ResumeStreamResponse) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{11}
}

func (x *ResumeStreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SeekStreamRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PositionSeconds int32                  `protobuf:"varint,2,opt,name=position_seconds,json=positionSeconds,proto3" json:"position_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SeekStreamRequest) Reset() {
	*x = SeekStreamRequest{}
	mi := &file_stream_stream_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeekStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekStreamRequest) ProtoMessage() {}

func (x *SeekStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekStreamRequest.ProtoReflect.Descriptor instead.
func (*SeekStreamRequest) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{12}
}

func (x *SeekStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SeekStreamRequest) GetPositionSeconds() int32 {
	if x != nil {
		return x.PositionSeconds
	}
	return 0
}

type SeekStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeekStreamResponse) Reset() {
	*x = SeekStreamResponse{}
	mi := &file_stream_stream_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeekStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekStreamResponse) ProtoMessage() {}

func (x *SeekStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekStreamResponse.ProtoReflect.Descriptor instead.
func (*SeekStreamResponse) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{13}
}

func (x *SeekStreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetQualitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQualitiesRequest) Reset() {
	*x = GetQualitiesRequest{}
	mi := &file_stream_stream_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQualitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQualitiesRequest) ProtoMessage() {}

func (x *GetQualitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQualitiesRequest.ProtoReflect.Descriptor instead.
func (*GetQualitiesRequest) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{14}
}

func (x *GetQualitiesRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type GetQualitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qualities     []Quality              `protobuf:"varint,1,rep,packed,name=qualities,proto3,enum=stream.Quality" json:"qualities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQualitiesResponse) Reset() {
	*x = GetQualitiesResponse{}
	mi := &file_stream_stream_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQualitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQualitiesResponse) ProtoMessage() {}

func (x *GetQualitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQualitiesResponse.ProtoReflect.Descriptor instead.
func (*GetQualitiesResponse) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{15}
}

func (x *GetQualitiesResponse) GetQualities() []Quality {
	if x != nil {
		return x.Qualities
	}
	return nil
}

type SetQualityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Quality       Quality                `protobuf:"varint,2,opt,name=quality,proto3,enum=stream.Quality" json:"quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetQualityRequest) Reset() {
	*x = SetQualityRequest{}
	mi := &file_stream_stream_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetQualityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetQualityRequest) ProtoMessage() {}

func (x *SetQualityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetQualityRequest.ProtoReflect.Descriptor instead.
func (*SetQualityRequest) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{16}
}

func (x *SetQualityRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetQualityRequest) GetQuality() Quality {
	if x != nil {
		return x.Quality
	}
	return Quality_Q_480P
}

type SetQualityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetQualityResponse) Reset() {
	*x = SetQualityResponse{}
	mi := &file_stream_stream_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetQualityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetQualityResponse) ProtoMessage() {}

func (x *SetQualityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetQualityResponse.ProtoReflect.Descriptor instead.
func (*SetQualityResponse) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{17}
}

func (x *SetQualityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSubtitlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubtitlesRequest) Reset() {
	*x = GetSubtitlesRequest{}
	mi := &file_stream_stream_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubtitlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubtitlesRequest) ProtoMessage() {}

func (x *GetSubtitlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubtitlesRequest.ProtoReflect.Descriptor instead.
func (*GetSubtitlesRequest) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{18}
}

func (x *GetSubtitlesRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type GetSubtitlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subtitles     []*Subtitle            `protobuf:"bytes,1,rep,name=subtitles,proto3" json:"subtitles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubtitlesResponse) Reset() {
	*x = GetSubtitlesResponse{}
	mi := &file_stream_stream_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubtitlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubtitlesResponse) ProtoMessage() {}

func (x *GetSubtitlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubtitlesResponse.ProtoReflect.Descriptor instead.
func (*GetSubtitlesResponse) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{19}
}

func (x *GetSubtitlesResponse) GetSubtitles() []*Subtitle {
	if x != nil {
		return x.Subtitles
	}
	return nil
}

type GetSubtitlesByLangRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubtitlesByLangRequest) Reset() {
	*x = GetSubtitlesByLangRequest{}
	mi := &file_stream_stream_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubtitlesByLangRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubtitlesByLangRequest) ProtoMessage() {}

func (x *GetSubtitlesByLangRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubtitlesByLangRequest.ProtoReflect.Descriptor instead.
func (*GetSubtitlesByLangRequest) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{20}
}

func (x *GetSubtitlesByLangRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *GetSubtitlesByLangRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type GetSubtitlesByLangResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subtitle      *Subtitle              `protobuf:"bytes,1,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubtitlesByLangResponse) Reset() {
	*x = GetSubtitlesByLangResponse{}
	mi := &file_stream_stream_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubtitlesByLangResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubtitlesByLangResponse) ProtoMessage() {}

func (x *GetSubtitlesByLangResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubtitlesByLangResponse.ProtoReflect.Descriptor instead.
func (*GetSubtitlesByLangResponse) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{21}
}

func (x *GetSubtitlesByLangResponse) GetSubtitle() *Subtitle {
	if x != nil {
		return x.Subtitle
	}
	return nil
}

type GetActiveSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveSessionsRequest) Reset() {
	*x = GetActiveSessionsRequest{}
	mi := &file_stream_stream_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveSessionsRequest) ProtoMessage() {}

func (x *GetActiveSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetActiveSessionsRequest) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{22}
}

func (x *GetActiveSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetActiveSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveSessionsResponse) Reset() {
	*x = GetActiveSessionsResponse{}
	mi := &file_stream_stream_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveSessionsResponse) ProtoMessage() {}

func (x *GetActiveSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetActiveSessionsResponse) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{23}
}

func (x *GetActiveSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *GetActiveSessionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetPreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreviewRequest) Reset() {
	*x = GetPreviewRequest{}
	mi := &file_stream_stream_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreviewRequest) ProtoMessage() {}

func (x *GetPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreviewRequest.ProtoReflect.Descriptor instead.
func (*GetPreviewRequest) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{24}
}

func (x *GetPreviewRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type GetPreviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreviewUrl    string                 `protobuf:"bytes,1,opt,name=preview_url,json=previewUrl,proto3" json:"preview_url,omitempty"`
	TrailerUrl    string                 `protobuf:"bytes,2,opt,name=trailer_url,json=trailerUrl,proto3" json:"trailer_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreviewResponse) Reset() {
	*x = GetPreviewResponse{}
	mi := &file_stream_stream_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreviewResponse) ProtoMessage() {}

func (x *GetPreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_stream_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreviewResponse.ProtoReflect.Descriptor instead.
func (*GetPreviewResponse) Descriptor() ([]byte, []int) {
	return file_stream_stream_proto_rawDescGZIP(), []int{25}
}

func (x *GetPreviewResponse) GetPreviewUrl() string {
	if x != nil {
		return x.PreviewUrl
	}
	return ""
}

func (x *GetPreviewResponse) GetTrailerUrl() string {
	if x != nil {
		return x.TrailerUrl
	}
	return ""
}

var File_stream_stream_proto protoreflect.FileDescriptor

const file_stream_stream_proto_rawDesc = "" +
	"\n" +
	"\x13stream/stream.proto\x12\x06stream\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bmovie_id\x18\x03 \x01(\tR\amovieId\x12)\n" +
	"\x10position_seconds\x18\x04 \x01(\x05R\x0fpositionSeconds\x12)\n" +
	"\aquality\x18\x05 \x01(\x0e2\x0f.stream.QualityR\aquality\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.stream.SessionStatusR\x06status\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"O\n" +
	"\bSubtitle\x12\x12\n" +
	"\x04lang\x18\x01 \x01(\tR\x04lang\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x19\n" +
	"\bfile_url\x18\x03 \x01(\tR\afileUrl\"s\n" +
	"\x12StartStreamRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\tR\amovieId\x12)\n" +
	"\aquality\x18\x03 \x01(\x0e2\x0f.stream.QualityR\aquality\"@\n" +
	"\x13StartStreamResponse\x12)\n" +
	"\asession\x18\x01 \x01(\v2\x0f.stream.SessionR\asession\"2\n" +
	"\x11StopStreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"W\n" +
	"\x12StopStreamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fwatched_seconds\x18\x02 \x01(\x05R\x0ewatchedSeconds\"7\n" +
	"\x16GetStreamStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"D\n" +
	"\x17GetStreamStatusResponse\x12)\n" +
	"\asession\x18\x01 \x01(\v2\x0f.stream.SessionR\asession\"^\n" +
	"\x12PauseStreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x10position_seconds\x18\x02 \x01(\x05R\x0fpositionSeconds\"/\n" +
	"\x13PauseStreamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\x13ResumeStreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"0\n" +
	"\x14ResumeStreamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"]\n" +
	"\x11SeekStreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x10position_seconds\x18\x02 \x01(\x05R\x0fpositionSeconds\".\n" +
	"\x12SeekStreamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x13GetQualitiesRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\"E\n" +
	"\x14GetQualitiesResponse\x12-\n" +
	"\tqualities\x18\x01 \x03(\x0e2\x0f.stream.QualityR\tqualities\"]\n" +
	"\x11SetQualityRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\aquality\x18\x02 \x01(\x0e2\x0f.stream.QualityR\aquality\".\n" +
	"\x12SetQualityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x13GetSubtitlesRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\"F\n" +
	"\x14GetSubtitlesResponse\x12.\n" +
	"\tsubtitles\x18\x01 \x03(\v2\x10.stream.SubtitleR\tsubtitles\"J\n" +
	"\x19GetSubtitlesByLangRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"J\n" +
	"\x1aGetSubtitlesByLangResponse\x12,\n" +
	"\bsubtitle\x18\x01 \x01(\v2\x10.stream.SubtitleR\bsubtitle\"0\n" +
	"\x18GetActiveSessionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"^\n" +
	"\x19GetActiveSessionsResponse\x12+\n" +
	"\bsessions\x18\x01 \x03(\v2\x0f.stream.SessionR\bsessions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\".\n" +
	"\x11GetPreviewRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\"V\n" +
	"\x12GetPreviewResponse\x12\x1f\n" +
	"\vpreview_url\x18\x01 \x01(\tR\n" +
	"previewUrl\x12\x1f\n" +
	"\vtrailer_url\x18\x02 \x01(\tR\n" +
	"trailerUrl*C\n" +
	"\rSessionStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPLAYING\x10\x01\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x02\x12\f\n" +
	"\bFINISHED\x10\x03*.\n" +
	"\aQuality\x12\n" +
	"\n" +
	"\x06Q_480P\x10\x00\x12\n" +
	"\n" +
	"\x06Q_720P\x10\x01\x12\v\n" +
	"\aQ_1080P\x10\x022\x9f\a\n" +
	"\rStreamService\x12F\n" +
	"\vStartStream\x12\x1a.stream.StartStreamRequest\x1a\x1b.stream.StartStreamResponse\x12C\n" +
	"\n" +
	"StopStream\x12\x19.stream.StopStreamRequest\x1a\x1a.stream.StopStreamResponse\x12R\n" +
	"\x0fGetStreamStatus\x12\x1e.stream.GetStreamStatusRequest\x1a\x1f.stream.GetStreamStatusResponse\x12F\n" +
	"\vPauseStream\x12\x1a.stream.PauseStreamRequest\x1a\x1b.stream.PauseStreamResponse\x12I\n" +
	"\fResumeStream\x12\x1b.stream.ResumeStreamRequest\x1a\x1c.stream.ResumeStreamResponse\x12C\n" +
	"\n" +
	"SeekStream\x12\x19.stream.SeekStreamRequest\x1a\x1a.stream.SeekStreamResponse\x12I\n" +
	"\fGetQualities\x12\x1b.stream.GetQualitiesRequest\x1a\x1c.stream.GetQualitiesResponse\x12C\n" +
	"\n" +
	"SetQuality\x12\x19.stream.SetQualityRequest\x1a\x1a.stream.SetQualityResponse\x12I\n" +
	"\fGetSubtitles\x12\x1b.stream.GetSubtitlesRequest\x1a\x1c.stream.GetSubtitlesResponse\x12[\n" +
	"\x12GetSubtitlesByLang\x12!.stream.GetSubtitlesByLangRequest\x1a\".stream.GetSubtitlesByLangResponse\x12X\n" +
	"\x11GetActiveSessions\x12 .stream.GetActiveSessionsRequest\x1a!.stream.GetActiveSessionsResponse\x12C\n" +
	"\n" +
	"GetPreview\x12\x19.stream.GetPreviewRequest\x1a\x1a.stream.GetPreviewResponseB7Z5github.com/Nalatka/GoMovieService/proto/stream;streamb\x06proto3"

var (
	file_stream_stream_proto_rawDescOnce sync.Once
	file_stream_stream_proto_rawDescData []byte
)

func file_stream_stream_proto_rawDescGZIP() []byte {
	file_stream_stream_proto_rawDescOnce.Do(func() {
		file_stream_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_stream_proto_rawDesc), len(file_stream_stream_proto_rawDesc)))
	})
	return file_stream_stream_proto_rawDescData
}

var file_stream_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_stream_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_stream_stream_proto_goTypes = []any{
	(SessionStatus)(0),                 // 0: stream.SessionStatus
	(Quality)(0),                       // 1: stream.Quality
	(*Session)(nil),                    // 2: stream.Session
	(*Subtitle)(nil),                   // 3: stream.Subtitle
	(*StartStreamRequest)(nil),         // 4: stream.StartStreamRequest
	(*StartStreamResponse)(nil),        // 5: stream.StartStreamResponse
	(*StopStreamRequest)(nil),          // 6: stream.StopStreamRequest
	(*StopStreamResponse)(nil),         // 7: stream.StopStreamResponse
	(*GetStreamStatusRequest)(nil),     // 8: stream.GetStreamStatusRequest
	(*GetStreamStatusResponse)(nil),    // 9: stream.GetStreamStatusResponse
	(*PauseStreamRequest)(nil),         // 10: stream.PauseStreamRequest
	(*PauseStreamResponse)(nil),        // 11: stream.PauseStreamResponse
	(*ResumeStreamRequest)(nil),        // 12: stream.ResumeStreamRequest
	(*ResumeStreamResponse)(nil),       // 13: stream.ResumeStreamResponse
	(*SeekStreamRequest)(nil),          // 14: stream.SeekStreamRequest
	(*SeekStreamResponse)(nil),         // 15: stream.SeekStreamResponse
	(*GetQualitiesRequest)(nil),        // 16: stream.GetQualitiesRequest
	(*GetQualitiesResponse)(nil),       // 17: stream.GetQualitiesResponse
	(*SetQualityRequest)(nil),          // 18: stream.SetQualityRequest
	(*SetQualityResponse)(nil),         // 19: stream.SetQualityResponse
	(*GetSubtitlesRequest)(nil),        // 20: stream.GetSubtitlesRequest
	(*GetSubtitlesResponse)(nil),       // 21: stream.GetSubtitlesResponse
	(*GetSubtitlesByLangRequest)(nil),  // 22: stream.GetSubtitlesByLangRequest
	(*GetSubtitlesByLangResponse)(nil), // 23: stream.GetSubtitlesByLangResponse
	(*GetActiveSessionsRequest)(nil),   // 24: stream.GetActiveSessionsRequest
	(*GetActiveSessionsResponse)(nil),  // 25: stream.GetActiveSessionsResponse
	(*GetPreviewRequest)(nil),          // 26: stream.GetPreviewRequest
	(*GetPreviewResponse)(nil),         // 27: stream.GetPreviewResponse
	(*timestamppb.Timestamp)(nil),      // 28: google.protobuf.Timestamp
}
var file_stream_stream_proto_depIdxs = []int32{
	1,  // 0: stream.Session.quality:type_name -> stream.Quality
	0,  // 1: stream.Session.status:type_name -> stream.SessionStatus
	28, // 2: stream.Session.started_at:type_name -> google.protobuf.Timestamp
	28, // 3: stream.Session.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: stream.StartStreamRequest.quality:type_name -> stream.Quality
	2,  // 5: stream.StartStreamResponse.session:type_name -> stream.Session
	2,  // 6: stream.GetStreamStatusResponse.session:type_name -> stream.Session
	1,  // 7: stream.GetQualitiesResponse.qualities:type_name -> stream.Quality
	1,  // 8: stream.SetQualityRequest.quality:type_name -> stream.Quality
	3,  // 9: stream.GetSubtitlesResponse.subtitles:type_name -> stream.Subtitle
	3,  // 10: stream.GetSubtitlesByLangResponse.subtitle:type_name -> stream.Subtitle
	2,  // 11: stream.GetActiveSessionsResponse.sessions:type_name -> stream.Session
	4,  // 12: stream.StreamService.StartStream:input_type -> stream.StartStreamRequest
	6,  // 13: stream.StreamService.StopStream:input_type -> stream.StopStreamRequest
	8,  // 14: stream.StreamService.GetStreamStatus:input_type -> stream.GetStreamStatusRequest
	10, // 15: stream.StreamService.PauseStream:input_type -> stream.PauseStreamRequest
	12, // 16: stream.StreamService.ResumeStream:input_type -> stream.ResumeStreamRequest
	14, // 17: stream.StreamService.SeekStream:input_type -> stream.SeekStreamRequest
	16, // 18: stream.StreamService.GetQualities:input_type -> stream.GetQualitiesRequest
	18, // 19: stream.StreamService.SetQuality:input_type -> stream.SetQualityRequest
	20, // 20: stream.StreamService.GetSubtitles:input_type -> stream.GetSubtitlesRequest
	22, // 21: stream.StreamService.GetSubtitlesByLang:input_type -> stream.GetSubtitlesByLangRequest
	24, // 22: stream.StreamService.GetActiveSessions:input_type -> stream.GetActiveSessionsRequest
	26, // 23: stream.StreamService.GetPreview:input_type -> stream.GetPreviewRequest
	5,  // 24: stream.StreamService.StartStream:output_type -> stream.StartStreamResponse
	7,  // 25: stream.StreamService.StopStream:output_type -> stream.StopStreamResponse
	9,  // 26: stream.StreamService.GetStreamStatus:output_type -> stream.GetStreamStatusResponse
	11, // 27: stream.StreamService.PauseStream:output_type -> stream.PauseStreamResponse
	13, // 28: stream.StreamService.ResumeStream:output_type -> stream.ResumeStreamResponse
	15, // 29: stream.StreamService.SeekStream:output_type -> stream.SeekStreamResponse
	17, // 30: stream.StreamService.GetQualities:output_type -> stream.GetQualitiesResponse
	19, // 31: stream.StreamService.SetQuality:output_type -> stream.SetQualityResponse
	21, // 32: stream.StreamService.GetSubtitles:output_type -> stream.GetSubtitlesResponse
	23, // 33: stream.StreamService.GetSubtitlesByLang:output_type -> stream.GetSubtitlesByLangResponse
	25, // 34: stream.StreamService.GetActiveSessions:output_type -> stream.GetActiveSessionsResponse
	27, // 35: stream.StreamService.GetPreview:output_type -> stream.GetPreviewResponse
	24, // [24:36] is the sub-list for method output_type
	12, // [12:24] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_stream_stream_proto_init() }
func file_stream_stream_proto_init() {
	if File_stream_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_stream_proto_rawDesc), len(file_stream_stream_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stream_stream_proto_goTypes,
		DependencyIndexes: file_stream_stream_proto_depIdxs,
		EnumInfos:         file_stream_stream_proto_enumTypes,
		MessageInfos:      file_stream_stream_proto_msgTypes,
	}.Build()
	File_stream_stream_proto = out.File
	file_stream_stream_proto_goTypes = nil
	file_stream_stream_proto_depIdxs = nil
}
