// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/content.proto

package content

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Movie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	GenreId       int64                  `protobuf:"varint,5,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
	GenreName     string                 `protobuf:"bytes,6,opt,name=genre_name,json=genreName,proto3" json:"genre_name,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,7,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	PosterUrl     string                 `protobuf:"bytes,8,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	DurationSec   int32                  `protobuf:"varint,9,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	AvgRating     float64                `protobuf:"fixed64,10,opt,name=avg_rating,json=avgRating,proto3" json:"avg_rating,omitempty"`
	Views         int64                  `protobuf:"varint,11,opt,name=views,proto3" json:"views,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_proto_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{0}
}

func (x *Movie) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Movie) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Movie) GetGenreId() int64 {
	if x != nil {
		return x.GenreId
	}
	return 0
}

func (x *Movie) GetGenreName() string {
	if x != nil {
		return x.GenreName
	}
	return ""
}

func (x *Movie) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Movie) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *Movie) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *Movie) GetAvgRating() float64 {
	if x != nil {
		return x.AvgRating
	}
	return 0
}

func (x *Movie) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *Movie) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Genre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genre) Reset() {
	*x = Genre{}
	mi := &file_proto_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{1}
}

func (x *Genre) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Genre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	GenreId       int64                  `protobuf:"varint,4,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,5,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	PosterUrl     string                 `protobuf:"bytes,6,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	DurationSec   int32                  `protobuf:"varint,7,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMovieRequest) Reset() {
	*x = CreateMovieRequest{}
	mi := &file_proto_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieRequest) ProtoMessage() {}

func (x *CreateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieRequest.ProtoReflect.Descriptor instead.
func (*CreateMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMovieRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMovieRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateMovieRequest) GetGenreId() int64 {
	if x != nil {
		return x.GenreId
	}
	return 0
}

func (x *CreateMovieRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *CreateMovieRequest) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *CreateMovieRequest) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

type CreateMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *Movie                 `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMovieResponse) Reset() {
	*x = CreateMovieResponse{}
	mi := &file_proto_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieResponse) ProtoMessage() {}

func (x *CreateMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieResponse.ProtoReflect.Descriptor instead.
func (*CreateMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMovieResponse) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type GetMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       int64                  `protobuf:"varint,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieRequest) Reset() {
	*x = GetMovieRequest{}
	mi := &file_proto_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieRequest) ProtoMessage() {}

func (x *GetMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieRequest.ProtoReflect.Descriptor instead.
func (*GetMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{4}
}

func (x *GetMovieRequest) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type GetMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *Movie                 `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieResponse) Reset() {
	*x = GetMovieResponse{}
	mi := &file_proto_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieResponse) ProtoMessage() {}

func (x *GetMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieResponse.ProtoReflect.Descriptor instead.
func (*GetMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{5}
}

func (x *GetMovieResponse) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type UpdateMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       int64                  `protobuf:"varint,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	GenreId       int64                  `protobuf:"varint,5,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,6,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	PosterUrl     string                 `protobuf:"bytes,7,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	DurationSec   int32                  `protobuf:"varint,8,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMovieRequest) Reset() {
	*x = UpdateMovieRequest{}
	mi := &file_proto_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieRequest) ProtoMessage() {}

func (x *UpdateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieRequest.ProtoReflect.Descriptor instead.
func (*UpdateMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMovieRequest) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

func (x *UpdateMovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateMovieRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateMovieRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *UpdateMovieRequest) GetGenreId() int64 {
	if x != nil {
		return x.GenreId
	}
	return 0
}

func (x *UpdateMovieRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *UpdateMovieRequest) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *UpdateMovieRequest) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

type UpdateMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *Movie                 `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMovieResponse) Reset() {
	*x = UpdateMovieResponse{}
	mi := &file_proto_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieResponse) ProtoMessage() {}

func (x *UpdateMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieResponse.ProtoReflect.Descriptor instead.
func (*UpdateMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMovieResponse) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type DeleteMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       int64                  `protobuf:"varint,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMovieRequest) Reset() {
	*x = DeleteMovieRequest{}
	mi := &file_proto_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieRequest) ProtoMessage() {}

func (x *DeleteMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieRequest.ProtoReflect.Descriptor instead.
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMovieRequest) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type DeleteMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMovieResponse) Reset() {
	*x = DeleteMovieResponse{}
	mi := &file_proto_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieResponse) ProtoMessage() {}

func (x *DeleteMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieResponse.ProtoReflect.Descriptor instead.
func (*DeleteMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMovieResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListMoviesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMoviesRequest) Reset() {
	*x = ListMoviesRequest{}
	mi := &file_proto_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMoviesRequest) ProtoMessage() {}

func (x *ListMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMoviesRequest.ProtoReflect.Descriptor instead.
func (*ListMoviesRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{10}
}

func (x *ListMoviesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMoviesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMoviesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*Movie               `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMoviesResponse) Reset() {
	*x = ListMoviesResponse{}
	mi := &file_proto_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMoviesResponse) ProtoMessage() {}

func (x *ListMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMoviesResponse.ProtoReflect.Descriptor instead.
func (*ListMoviesResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{11}
}

func (x *ListMoviesResponse) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

func (x *ListMoviesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SearchMoviesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMoviesRequest) Reset() {
	*x = SearchMoviesRequest{}
	mi := &file_proto_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMoviesRequest) ProtoMessage() {}

func (x *SearchMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMoviesRequest.ProtoReflect.Descriptor instead.
func (*SearchMoviesRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{12}
}

func (x *SearchMoviesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchMoviesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchMoviesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchMoviesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*Movie               `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMoviesResponse) Reset() {
	*x = SearchMoviesResponse{}
	mi := &file_proto_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMoviesResponse) ProtoMessage() {}

func (x *SearchMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMoviesResponse.ProtoReflect.Descriptor instead.
func (*SearchMoviesResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{13}
}

func (x *SearchMoviesResponse) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

func (x *SearchMoviesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetGenresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenresRequest) Reset() {
	*x = GetGenresRequest{}
	mi := &file_proto_content_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenresRequest) ProtoMessage() {}

func (x *GetGenresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenresRequest.ProtoReflect.Descriptor instead.
func (*GetGenresRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{14}
}

type GetGenresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genres        []*Genre               `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenresResponse) Reset() {
	*x = GetGenresResponse{}
	mi := &file_proto_content_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenresResponse) ProtoMessage() {}

func (x *GetGenresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenresResponse.ProtoReflect.Descriptor instead.
func (*GetGenresResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{15}
}

func (x *GetGenresResponse) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

type GetMoviesByGenreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenreId       int64                  `protobuf:"varint,1,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoviesByGenreRequest) Reset() {
	*x = GetMoviesByGenreRequest{}
	mi := &file_proto_content_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoviesByGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviesByGenreRequest) ProtoMessage() {}

func (x *GetMoviesByGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviesByGenreRequest.ProtoReflect.Descriptor instead.
func (*GetMoviesByGenreRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{16}
}

func (x *GetMoviesByGenreRequest) GetGenreId() int64 {
	if x != nil {
		return x.GenreId
	}
	return 0
}

func (x *GetMoviesByGenreRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMoviesByGenreRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMoviesByGenreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*Movie               `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoviesByGenreResponse) Reset() {
	*x = GetMoviesByGenreResponse{}
	mi := &file_proto_content_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoviesByGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviesByGenreResponse) ProtoMessage() {}

func (x *GetMoviesByGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviesByGenreResponse.ProtoReflect.Descriptor instead.
func (*GetMoviesByGenreResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{17}
}

func (x *GetMoviesByGenreResponse) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

func (x *GetMoviesByGenreResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RateMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       int64                  `protobuf:"varint,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateMovieRequest) Reset() {
	*x = RateMovieRequest{}
	mi := &file_proto_content_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateMovieRequest) ProtoMessage() {}

func (x *RateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateMovieRequest.ProtoReflect.Descriptor instead.
func (*RateMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{18}
}

func (x *RateMovieRequest) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

func (x *RateMovieRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RateMovieRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RateMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewAvg        float64                `protobuf:"fixed64,2,opt,name=new_avg,json=newAvg,proto3" json:"new_avg,omitempty"`
	TotalVotes    int64                  `protobuf:"varint,3,opt,name=total_votes,json=totalVotes,proto3" json:"total_votes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateMovieResponse) Reset() {
	*x = RateMovieResponse{}
	mi := &file_proto_content_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateMovieResponse) ProtoMessage() {}

func (x *RateMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateMovieResponse.ProtoReflect.Descriptor instead.
func (*RateMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{19}
}

func (x *RateMovieResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RateMovieResponse) GetNewAvg() float64 {
	if x != nil {
		return x.NewAvg
	}
	return 0
}

func (x *RateMovieResponse) GetTotalVotes() int64 {
	if x != nil {
		return x.TotalVotes
	}
	return 0
}

type GetMovieRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       int64                  `protobuf:"varint,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieRatingRequest) Reset() {
	*x = GetMovieRatingRequest{}
	mi := &file_proto_content_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieRatingRequest) ProtoMessage() {}

func (x *GetMovieRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieRatingRequest.ProtoReflect.Descriptor instead.
func (*GetMovieRatingRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{20}
}

func (x *GetMovieRatingRequest) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type GetMovieRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvgRating     float64                `protobuf:"fixed64,1,opt,name=avg_rating,json=avgRating,proto3" json:"avg_rating,omitempty"`
	TotalVotes    int64                  `protobuf:"varint,2,opt,name=total_votes,json=totalVotes,proto3" json:"total_votes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieRatingResponse) Reset() {
	*x = GetMovieRatingResponse{}
	mi := &file_proto_content_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieRatingResponse) ProtoMessage() {}

func (x *GetMovieRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieRatingResponse.ProtoReflect.Descriptor instead.
func (*GetMovieRatingResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{21}
}

func (x *GetMovieRatingResponse) GetAvgRating() float64 {
	if x != nil {
		return x.AvgRating
	}
	return 0
}

func (x *GetMovieRatingResponse) GetTotalVotes() int64 {
	if x != nil {
		return x.TotalVotes
	}
	return 0
}

type GetTopMoviesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopMoviesRequest) Reset() {
	*x = GetTopMoviesRequest{}
	mi := &file_proto_content_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopMoviesRequest) ProtoMessage() {}

func (x *GetTopMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopMoviesRequest.ProtoReflect.Descriptor instead.
func (*GetTopMoviesRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{22}
}

func (x *GetTopMoviesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTopMoviesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*Movie               `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopMoviesResponse) Reset() {
	*x = GetTopMoviesResponse{}
	mi := &file_proto_content_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopMoviesResponse) ProtoMessage() {}

func (x *GetTopMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopMoviesResponse.ProtoReflect.Descriptor instead.
func (*GetTopMoviesResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{23}
}

func (x *GetTopMoviesResponse) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

type GetSimilarMoviesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       int64                  `protobuf:"varint,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimilarMoviesRequest) Reset() {
	*x = GetSimilarMoviesRequest{}
	mi := &file_proto_content_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarMoviesRequest) ProtoMessage() {}

func (x *GetSimilarMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarMoviesRequest.ProtoReflect.Descriptor instead.
func (*GetSimilarMoviesRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{24}
}

func (x *GetSimilarMoviesRequest) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

func (x *GetSimilarMoviesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetSimilarMoviesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*Movie               `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimilarMoviesResponse) Reset() {
	*x = GetSimilarMoviesResponse{}
	mi := &file_proto_content_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarMoviesResponse) ProtoMessage() {}

func (x *GetSimilarMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarMoviesResponse.ProtoReflect.Descriptor instead.
func (*GetSimilarMoviesResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{25}
}

func (x *GetSimilarMoviesResponse) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

var File_proto_content_proto protoreflect.FileDescriptor

const file_proto_content_proto_rawDesc = "" +
	"\n" +
	"\x13proto/content.proto\x12\acontent\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x02\n" +
	"\x05Movie\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x19\n" +
	"\bgenre_id\x18\x05 \x01(\x03R\agenreId\x12\x1d\n" +
	"\n" +
	"genre_name\x18\x06 \x01(\tR\tgenreName\x12\x1b\n" +
	"\tvideo_url\x18\a \x01(\tR\bvideoUrl\x12\x1d\n" +
	"\n" +
	"poster_url\x18\b \x01(\tR\tposterUrl\x12!\n" +
	"\fduration_sec\x18\t \x01(\x05R\vdurationSec\x12\x1d\n" +
	"\n" +
	"avg_rating\x18\n" +
	" \x01(\x01R\tavgRating\x12\x14\n" +
	"\x05views\x18\v \x01(\x03R\x05views\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"+\n" +
	"\x05Genre\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xda\x01\n" +
	"\x12CreateMovieRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x19\n" +
	"\bgenre_id\x18\x04 \x01(\x03R\agenreId\x12\x1b\n" +
	"\tvideo_url\x18\x05 \x01(\tR\bvideoUrl\x12\x1d\n" +
	"\n" +
	"poster_url\x18\x06 \x01(\tR\tposterUrl\x12!\n" +
	"\fduration_sec\x18\a \x01(\x05R\vdurationSec\";\n" +
	"\x13CreateMovieResponse\x12$\n" +
	"\x05movie\x18\x01 \x01(\v2\x0e.content.MovieR\x05movie\",\n" +
	"\x0fGetMovieRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\x03R\amovieId\"8\n" +
	"\x10GetMovieResponse\x12$\n" +
	"\x05movie\x18\x01 \x01(\v2\x0e.content.MovieR\x05movie\"\xf5\x01\n" +
	"\x12UpdateMovieRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\x03R\amovieId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x19\n" +
	"\bgenre_id\x18\x05 \x01(\x03R\agenreId\x12\x1b\n" +
	"\tvideo_url\x18\x06 \x01(\tR\bvideoUrl\x12\x1d\n" +
	"\n" +
	"poster_url\x18\a \x01(\tR\tposterUrl\x12!\n" +
	"\fduration_sec\x18\b \x01(\x05R\vdurationSec\";\n" +
	"\x13UpdateMovieResponse\x12$\n" +
	"\x05movie\x18\x01 \x01(\v2\x0e.content.MovieR\x05movie\"/\n" +
	"\x12DeleteMovieRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\x03R\amovieId\"/\n" +
	"\x13DeleteMovieResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"=\n" +
	"\x11ListMoviesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"R\n" +
	"\x12ListMoviesResponse\x12&\n" +
	"\x06movies\x18\x01 \x03(\v2\x0e.content.MovieR\x06movies\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"U\n" +
	"\x13SearchMoviesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"T\n" +
	"\x14SearchMoviesResponse\x12&\n" +
	"\x06movies\x18\x01 \x03(\v2\x0e.content.MovieR\x06movies\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x12\n" +
	"\x10GetGenresRequest\";\n" +
	"\x11GetGenresResponse\x12&\n" +
	"\x06genres\x18\x01 \x03(\v2\x0e.content.GenreR\x06genres\"^\n" +
	"\x17GetMoviesByGenreRequest\x12\x19\n" +
	"\bgenre_id\x18\x01 \x01(\x03R\agenreId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"X\n" +
	"\x18GetMoviesByGenreResponse\x12&\n" +
	"\x06movies\x18\x01 \x03(\v2\x0e.content.MovieR\x06movies\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\\\n" +
	"\x10RateMovieRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\x03R\amovieId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\"g\n" +
	"\x11RateMovieResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\anew_avg\x18\x02 \x01(\x01R\x06newAvg\x12\x1f\n" +
	"\vtotal_votes\x18\x03 \x01(\x03R\n" +
	"totalVotes\"2\n" +
	"\x15GetMovieRatingRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\x03R\amovieId\"X\n" +
	"\x16GetMovieRatingResponse\x12\x1d\n" +
	"\n" +
	"avg_rating\x18\x01 \x01(\x01R\tavgRating\x12\x1f\n" +
	"\vtotal_votes\x18\x02 \x01(\x03R\n" +
	"totalVotes\"+\n" +
	"\x13GetTopMoviesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\">\n" +
	"\x14GetTopMoviesResponse\x12&\n" +
	"\x06movies\x18\x01 \x03(\v2\x0e.content.MovieR\x06movies\"J\n" +
	"\x17GetSimilarMoviesRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\x03R\amovieId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"B\n" +
	"\x18GetSimilarMoviesResponse\x12&\n" +
	"\x06movies\x18\x01 \x03(\v2\x0e.content.MovieR\x06movies2\x9d\a\n" +
	"\x0eContentService\x12H\n" +
	"\vCreateMovie\x12\x1b.content.CreateMovieRequest\x1a\x1c.content.CreateMovieResponse\x12?\n" +
	"\bGetMovie\x12\x18.content.GetMovieRequest\x1a\x19.content.GetMovieResponse\x12H\n" +
	"\vUpdateMovie\x12\x1b.content.UpdateMovieRequest\x1a\x1c.content.UpdateMovieResponse\x12H\n" +
	"\vDeleteMovie\x12\x1b.content.DeleteMovieRequest\x1a\x1c.content.DeleteMovieResponse\x12E\n" +
	"\n" +
	"ListMovies\x12\x1a.content.ListMoviesRequest\x1a\x1b.content.ListMoviesResponse\x12K\n" +
	"\fSearchMovies\x12\x1c.content.SearchMoviesRequest\x1a\x1d.content.SearchMoviesResponse\x12B\n" +
	"\tGetGenres\x12\x19.content.GetGenresRequest\x1a\x1a.content.GetGenresResponse\x12W\n" +
	"\x10GetMoviesByGenre\x12 .content.GetMoviesByGenreRequest\x1a!.content.GetMoviesByGenreResponse\x12B\n" +
	"\tRateMovie\x12\x19.content.RateMovieRequest\x1a\x1a.content.RateMovieResponse\x12Q\n" +
	"\x0eGetMovieRating\x12\x1e.content.GetMovieRatingRequest\x1a\x1f.content.GetMovieRatingResponse\x12K\n" +
	"\fGetTopMovies\x12\x1c.content.GetTopMoviesRequest\x1a\x1d.content.GetTopMoviesResponse\x12W\n" +
	"\x10GetSimilarMovies\x12 .content.GetSimilarMoviesRequest\x1a!.content.GetSimilarMoviesResponseB\x1fZ\x1dmovie-streaming/proto/contentb\x06proto3"

var (
	file_proto_content_proto_rawDescOnce sync.Once
	file_proto_content_proto_rawDescData []byte
)

func file_proto_content_proto_rawDescGZIP() []byte {
	file_proto_content_proto_rawDescOnce.Do(func() {
		file_proto_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_content_proto_rawDesc), len(file_proto_content_proto_rawDesc)))
	})
	return file_proto_content_proto_rawDescData
}

var file_proto_content_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_content_proto_goTypes = []any{
	(*Movie)(nil),                    // 0: content.Movie
	(*Genre)(nil),                    // 1: content.Genre
	(*CreateMovieRequest)(nil),       // 2: content.CreateMovieRequest
	(*CreateMovieResponse)(nil),      // 3: content.CreateMovieResponse
	(*GetMovieRequest)(nil),          // 4: content.GetMovieRequest
	(*GetMovieResponse)(nil),         // 5: content.GetMovieResponse
	(*UpdateMovieRequest)(nil),       // 6: content.UpdateMovieRequest
	(*UpdateMovieResponse)(nil),      // 7: content.UpdateMovieResponse
	(*DeleteMovieRequest)(nil),       // 8: content.DeleteMovieRequest
	(*DeleteMovieResponse)(nil),      // 9: content.DeleteMovieResponse
	(*ListMoviesRequest)(nil),        // 10: content.ListMoviesRequest
	(*ListMoviesResponse)(nil),       // 11: content.ListMoviesResponse
	(*SearchMoviesRequest)(nil),      // 12: content.SearchMoviesRequest
	(*SearchMoviesResponse)(nil),     // 13: content.SearchMoviesResponse
	(*GetGenresRequest)(nil),         // 14: content.GetGenresRequest
	(*GetGenresResponse)(nil),        // 15: content.GetGenresResponse
	(*GetMoviesByGenreRequest)(nil),  // 16: content.GetMoviesByGenreRequest
	(*GetMoviesByGenreResponse)(nil), // 17: content.GetMoviesByGenreResponse
	(*RateMovieRequest)(nil),         // 18: content.RateMovieRequest
	(*RateMovieResponse)(nil),        // 19: content.RateMovieResponse
	(*GetMovieRatingRequest)(nil),    // 20: content.GetMovieRatingRequest
	(*GetMovieRatingResponse)(nil),   // 21: content.GetMovieRatingResponse
	(*GetTopMoviesRequest)(nil),      // 22: content.GetTopMoviesRequest
	(*GetTopMoviesResponse)(nil),     // 23: content.GetTopMoviesResponse
	(*GetSimilarMoviesRequest)(nil),  // 24: content.GetSimilarMoviesRequest
	(*GetSimilarMoviesResponse)(nil), // 25: content.GetSimilarMoviesResponse
	(*timestamppb.Timestamp)(nil),    // 26: google.protobuf.Timestamp
}
var file_proto_content_proto_depIdxs = []int32{
	26, // 0: content.Movie.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: content.CreateMovieResponse.movie:type_name -> content.Movie
	0,  // 2: content.GetMovieResponse.movie:type_name -> content.Movie
	0,  // 3: content.UpdateMovieResponse.movie:type_name -> content.Movie
	0,  // 4: content.ListMoviesResponse.movies:type_name -> content.Movie
	0,  // 5: content.SearchMoviesResponse.movies:type_name -> content.Movie
	1,  // 6: content.GetGenresResponse.genres:type_name -> content.Genre
	0,  // 7: content.GetMoviesByGenreResponse.movies:type_name -> content.Movie
	0,  // 8: content.GetTopMoviesResponse.movies:type_name -> content.Movie
	0,  // 9: content.GetSimilarMoviesResponse.movies:type_name -> content.Movie
	2,  // 10: content.ContentService.CreateMovie:input_type -> content.CreateMovieRequest
	4,  // 11: content.ContentService.GetMovie:input_type -> content.GetMovieRequest
	6,  // 12: content.ContentService.UpdateMovie:input_type -> content.UpdateMovieRequest
	8,  // 13: content.ContentService.DeleteMovie:input_type -> content.DeleteMovieRequest
	10, // 14: content.ContentService.ListMovies:input_type -> content.ListMoviesRequest
	12, // 15: content.ContentService.SearchMovies:input_type -> content.SearchMoviesRequest
	14, // 16: content.ContentService.GetGenres:input_type -> content.GetGenresRequest
	16, // 17: content.ContentService.GetMoviesByGenre:input_type -> content.GetMoviesByGenreRequest
	18, // 18: content.ContentService.RateMovie:input_type -> content.RateMovieRequest
	20, // 19: content.ContentService.GetMovieRating:input_type -> content.GetMovieRatingRequest
	22, // 20: content.ContentService.GetTopMovies:input_type -> content.GetTopMoviesRequest
	24, // 21: content.ContentService.GetSimilarMovies:input_type -> content.GetSimilarMoviesRequest
	3,  // 22: content.ContentService.CreateMovie:output_type -> content.CreateMovieResponse
	5,  // 23: content.ContentService.GetMovie:output_type -> content.GetMovieResponse
	7,  // 24: content.ContentService.UpdateMovie:output_type -> content.UpdateMovieResponse
	9,  // 25: content.ContentService.DeleteMovie:output_type -> content.DeleteMovieResponse
	11, // 26: content.ContentService.ListMovies:output_type -> content.ListMoviesResponse
	13, // 27: content.ContentService.SearchMovies:output_type -> content.SearchMoviesResponse
	15, // 28: content.ContentService.GetGenres:output_type -> content.GetGenresResponse
	17, // 29: content.ContentService.GetMoviesByGenre:output_type -> content.GetMoviesByGenreResponse
	19, // 30: content.ContentService.RateMovie:output_type -> content.RateMovieResponse
	21, // 31: content.ContentService.GetMovieRating:output_type -> content.GetMovieRatingResponse
	23, // 32: content.ContentService.GetTopMovies:output_type -> content.GetTopMoviesResponse
	25, // 33: content.ContentService.GetSimilarMovies:output_type -> content.GetSimilarMoviesResponse
	22, // [22:34] is the sub-list for method output_type
	10, // [10:22] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_content_proto_init() }
func file_proto_content_proto_init() {
	if File_proto_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_content_proto_rawDesc), len(file_proto_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_content_proto_goTypes,
		DependencyIndexes: file_proto_content_proto_depIdxs,
		MessageInfos:      file_proto_content_proto_msgTypes,
	}.Build()
	File_proto_content_proto = out.File
	file_proto_content_proto_goTypes = nil
	file_proto_content_proto_depIdxs = nil
}
